package Paquete.Pojos;
// Generated 3/03/2019 08:38:04 PM by Hibernate Tools 4.3.1



/**
 * Deuda generated by hbm2java
 */
public class Deuda  implements java.io.Serializable {


     private int idDeuda;
     private Equipo equipo;
     private Material material;
     private byte[] observacion;

    public Deuda() {
    }

    public Deuda(int idDeuda, Equipo equipo, Material material, byte[] observacion) {
       this.idDeuda = idDeuda;
       this.equipo = equipo;
       this.material = material;
       this.observacion = observacion;
    }
   
    public int getIdDeuda() {
        return this.idDeuda;
    }
    
    public void setIdDeuda(int idDeuda) {
        this.idDeuda = idDeuda;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }
    public byte[] getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(byte[] observacion) {
        this.observacion = observacion;
    }




}


