package Paquete.Pojos;
// Generated 3/03/2019 08:38:04 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Emergencias generated by hbm2java
 */
public class Emergencias  implements java.io.Serializable {


     private int idEmergencias;
     private Serializable nombre;
     private int telefono;
     private Serializable correo;
     private Set historialEmergencias = new HashSet(0);

    public Emergencias() {
    }

	
    public Emergencias(int idEmergencias, Serializable nombre, int telefono, Serializable correo) {
        this.idEmergencias = idEmergencias;
        this.nombre = nombre;
        this.telefono = telefono;
        this.correo = correo;
    }
    public Emergencias(int idEmergencias, Serializable nombre, int telefono, Serializable correo, Set historialEmergencias) {
       this.idEmergencias = idEmergencias;
       this.nombre = nombre;
       this.telefono = telefono;
       this.correo = correo;
       this.historialEmergencias = historialEmergencias;
    }
   
    public int getIdEmergencias() {
        return this.idEmergencias;
    }
    
    public void setIdEmergencias(int idEmergencias) {
        this.idEmergencias = idEmergencias;
    }
    public Serializable getNombre() {
        return this.nombre;
    }
    
    public void setNombre(Serializable nombre) {
        this.nombre = nombre;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public Serializable getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(Serializable correo) {
        this.correo = correo;
    }
    public Set getHistorialEmergencias() {
        return this.historialEmergencias;
    }
    
    public void setHistorialEmergencias(Set historialEmergencias) {
        this.historialEmergencias = historialEmergencias;
    }




}


