package Paquete.Pojos;
// Generated 3/03/2019 08:38:04 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * EquipoLaboratorio generated by hbm2java
 */
public class EquipoLaboratorio  implements java.io.Serializable {


     private int idEquipoLaboratorio;
     private Serializable nombre;
     private Serializable caracteristicas;
     private short existenciaInventario;
     private int cantidad;
     private Set equipoUtilizados = new HashSet(0);
     private Set historialEquipos = new HashSet(0);
     private Set datosVales = new HashSet(0);

    public EquipoLaboratorio() {
    }

	
    public EquipoLaboratorio(int idEquipoLaboratorio, Serializable nombre, Serializable caracteristicas, short existenciaInventario, int cantidad) {
        this.idEquipoLaboratorio = idEquipoLaboratorio;
        this.nombre = nombre;
        this.caracteristicas = caracteristicas;
        this.existenciaInventario = existenciaInventario;
        this.cantidad = cantidad;
    }
    public EquipoLaboratorio(int idEquipoLaboratorio, Serializable nombre, Serializable caracteristicas, short existenciaInventario, int cantidad, Set equipoUtilizados, Set historialEquipos, Set datosVales) {
       this.idEquipoLaboratorio = idEquipoLaboratorio;
       this.nombre = nombre;
       this.caracteristicas = caracteristicas;
       this.existenciaInventario = existenciaInventario;
       this.cantidad = cantidad;
       this.equipoUtilizados = equipoUtilizados;
       this.historialEquipos = historialEquipos;
       this.datosVales = datosVales;
    }
   
    public int getIdEquipoLaboratorio() {
        return this.idEquipoLaboratorio;
    }
    
    public void setIdEquipoLaboratorio(int idEquipoLaboratorio) {
        this.idEquipoLaboratorio = idEquipoLaboratorio;
    }
    public Serializable getNombre() {
        return this.nombre;
    }
    
    public void setNombre(Serializable nombre) {
        this.nombre = nombre;
    }
    public Serializable getCaracteristicas() {
        return this.caracteristicas;
    }
    
    public void setCaracteristicas(Serializable caracteristicas) {
        this.caracteristicas = caracteristicas;
    }
    public short getExistenciaInventario() {
        return this.existenciaInventario;
    }
    
    public void setExistenciaInventario(short existenciaInventario) {
        this.existenciaInventario = existenciaInventario;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Set getEquipoUtilizados() {
        return this.equipoUtilizados;
    }
    
    public void setEquipoUtilizados(Set equipoUtilizados) {
        this.equipoUtilizados = equipoUtilizados;
    }
    public Set getHistorialEquipos() {
        return this.historialEquipos;
    }
    
    public void setHistorialEquipos(Set historialEquipos) {
        this.historialEquipos = historialEquipos;
    }
    public Set getDatosVales() {
        return this.datosVales;
    }
    
    public void setDatosVales(Set datosVales) {
        this.datosVales = datosVales;
    }




}


