package Paquete.Pojos;
// Generated 3/03/2019 08:38:04 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private int idEquipo;
     private UnidadGrupo unidadGrupo;
     private Serializable nombre;
     private Set deudas = new HashSet(0);
     private Set vales = new HashSet(0);

    public Equipo() {
    }

	
    public Equipo(int idEquipo, UnidadGrupo unidadGrupo, Serializable nombre) {
        this.idEquipo = idEquipo;
        this.unidadGrupo = unidadGrupo;
        this.nombre = nombre;
    }
    public Equipo(int idEquipo, UnidadGrupo unidadGrupo, Serializable nombre, Set deudas, Set vales) {
       this.idEquipo = idEquipo;
       this.unidadGrupo = unidadGrupo;
       this.nombre = nombre;
       this.deudas = deudas;
       this.vales = vales;
    }
   
    public int getIdEquipo() {
        return this.idEquipo;
    }
    
    public void setIdEquipo(int idEquipo) {
        this.idEquipo = idEquipo;
    }
    public UnidadGrupo getUnidadGrupo() {
        return this.unidadGrupo;
    }
    
    public void setUnidadGrupo(UnidadGrupo unidadGrupo) {
        this.unidadGrupo = unidadGrupo;
    }
    public Serializable getNombre() {
        return this.nombre;
    }
    
    public void setNombre(Serializable nombre) {
        this.nombre = nombre;
    }
    public Set getDeudas() {
        return this.deudas;
    }
    
    public void setDeudas(Set deudas) {
        this.deudas = deudas;
    }
    public Set getVales() {
        return this.vales;
    }
    
    public void setVales(Set vales) {
        this.vales = vales;
    }




}


