package Paquete.Pojos;
// Generated 3/03/2019 08:38:04 PM by Hibernate Tools 4.3.1



/**
 * ListaGrupo generated by hbm2java
 */
public class ListaGrupo  implements java.io.Serializable {


     private int idListaGrupo;
     private UnidadGrupo unidadGrupo;
     private Usuarios usuarios;

    public ListaGrupo() {
    }

    public ListaGrupo(int idListaGrupo, UnidadGrupo unidadGrupo, Usuarios usuarios) {
       this.idListaGrupo = idListaGrupo;
       this.unidadGrupo = unidadGrupo;
       this.usuarios = usuarios;
    }
   
    public int getIdListaGrupo() {
        return this.idListaGrupo;
    }
    
    public void setIdListaGrupo(int idListaGrupo) {
        this.idListaGrupo = idListaGrupo;
    }
    public UnidadGrupo getUnidadGrupo() {
        return this.unidadGrupo;
    }
    
    public void setUnidadGrupo(UnidadGrupo unidadGrupo) {
        this.unidadGrupo = unidadGrupo;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }




}


