package Paquete.Pojos;
// Generated 3/03/2019 08:38:04 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Material generated by hbm2java
 */
public class Material  implements java.io.Serializable {


     private int idMaterial;
     private Serializable nombre;
     private int cantidad;
     private short existenciaInventario;
     private Serializable caracteristicas;
     private Set deudas = new HashSet(0);
     private Set datosVales = new HashSet(0);
     private Set materialUtilizados = new HashSet(0);

    public Material() {
    }

	
    public Material(int idMaterial, Serializable nombre, int cantidad, short existenciaInventario, Serializable caracteristicas) {
        this.idMaterial = idMaterial;
        this.nombre = nombre;
        this.cantidad = cantidad;
        this.existenciaInventario = existenciaInventario;
        this.caracteristicas = caracteristicas;
    }
    public Material(int idMaterial, Serializable nombre, int cantidad, short existenciaInventario, Serializable caracteristicas, Set deudas, Set datosVales, Set materialUtilizados) {
       this.idMaterial = idMaterial;
       this.nombre = nombre;
       this.cantidad = cantidad;
       this.existenciaInventario = existenciaInventario;
       this.caracteristicas = caracteristicas;
       this.deudas = deudas;
       this.datosVales = datosVales;
       this.materialUtilizados = materialUtilizados;
    }
   
    public int getIdMaterial() {
        return this.idMaterial;
    }
    
    public void setIdMaterial(int idMaterial) {
        this.idMaterial = idMaterial;
    }
    public Serializable getNombre() {
        return this.nombre;
    }
    
    public void setNombre(Serializable nombre) {
        this.nombre = nombre;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public short getExistenciaInventario() {
        return this.existenciaInventario;
    }
    
    public void setExistenciaInventario(short existenciaInventario) {
        this.existenciaInventario = existenciaInventario;
    }
    public Serializable getCaracteristicas() {
        return this.caracteristicas;
    }
    
    public void setCaracteristicas(Serializable caracteristicas) {
        this.caracteristicas = caracteristicas;
    }
    public Set getDeudas() {
        return this.deudas;
    }
    
    public void setDeudas(Set deudas) {
        this.deudas = deudas;
    }
    public Set getDatosVales() {
        return this.datosVales;
    }
    
    public void setDatosVales(Set datosVales) {
        this.datosVales = datosVales;
    }
    public Set getMaterialUtilizados() {
        return this.materialUtilizados;
    }
    
    public void setMaterialUtilizados(Set materialUtilizados) {
        this.materialUtilizados = materialUtilizados;
    }




}


