package Paquete.Pojos;
// Generated 3/03/2019 08:38:04 PM by Hibernate Tools 4.3.1



/**
 * MaterialUtilizado generated by hbm2java
 */
public class MaterialUtilizado  implements java.io.Serializable {


     private int idMaterialUtilizado;
     private Material material;
     private Practica practica;

    public MaterialUtilizado() {
    }

    public MaterialUtilizado(int idMaterialUtilizado, Material material, Practica practica) {
       this.idMaterialUtilizado = idMaterialUtilizado;
       this.material = material;
       this.practica = practica;
    }
   
    public int getIdMaterialUtilizado() {
        return this.idMaterialUtilizado;
    }
    
    public void setIdMaterialUtilizado(int idMaterialUtilizado) {
        this.idMaterialUtilizado = idMaterialUtilizado;
    }
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }
    public Practica getPractica() {
        return this.practica;
    }
    
    public void setPractica(Practica practica) {
        this.practica = practica;
    }




}


