package Paquete.Pojos;
// Generated 3/03/2019 08:38:04 PM by Hibernate Tools 4.3.1



/**
 * NotificacionesSesion generated by hbm2java
 */
public class NotificacionesSesion  implements java.io.Serializable {


     private int idNotificacion;
     private SesionDeLaboratorio sesionDeLaboratorio;
     private byte[] descripcion;
     private short estado;

    public NotificacionesSesion() {
    }

    public NotificacionesSesion(int idNotificacion, SesionDeLaboratorio sesionDeLaboratorio, byte[] descripcion, short estado) {
       this.idNotificacion = idNotificacion;
       this.sesionDeLaboratorio = sesionDeLaboratorio;
       this.descripcion = descripcion;
       this.estado = estado;
    }
   
    public int getIdNotificacion() {
        return this.idNotificacion;
    }
    
    public void setIdNotificacion(int idNotificacion) {
        this.idNotificacion = idNotificacion;
    }
    public SesionDeLaboratorio getSesionDeLaboratorio() {
        return this.sesionDeLaboratorio;
    }
    
    public void setSesionDeLaboratorio(SesionDeLaboratorio sesionDeLaboratorio) {
        this.sesionDeLaboratorio = sesionDeLaboratorio;
    }
    public byte[] getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(byte[] descripcion) {
        this.descripcion = descripcion;
    }
    public short getEstado() {
        return this.estado;
    }
    
    public void setEstado(short estado) {
        this.estado = estado;
    }




}


