package Paquete.Pojos;
// Generated 3/03/2019 08:38:04 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Practica generated by hbm2java
 */
public class Practica  implements java.io.Serializable {


     private int idPractica;
     private UnidadTematica unidadTematica;
     private Usuarios usuarios;
     private Date creacion;
     private Set materialUtilizados = new HashSet(0);
     private Set notificacionesPracticas = new HashSet(0);
     private DatosPractica datosPractica;
     private Set equipoUtilizados = new HashSet(0);
     private Set reactivosUtilizadoPracticas = new HashSet(0);

    public Practica() {
    }

	
    public Practica(int idPractica, UnidadTematica unidadTematica, Usuarios usuarios, Date creacion) {
        this.idPractica = idPractica;
        this.unidadTematica = unidadTematica;
        this.usuarios = usuarios;
        this.creacion = creacion;
    }
    public Practica(int idPractica, UnidadTematica unidadTematica, Usuarios usuarios, Date creacion, Set materialUtilizados, Set notificacionesPracticas, DatosPractica datosPractica, Set equipoUtilizados, Set reactivosUtilizadoPracticas) {
       this.idPractica = idPractica;
       this.unidadTematica = unidadTematica;
       this.usuarios = usuarios;
       this.creacion = creacion;
       this.materialUtilizados = materialUtilizados;
       this.notificacionesPracticas = notificacionesPracticas;
       this.datosPractica = datosPractica;
       this.equipoUtilizados = equipoUtilizados;
       this.reactivosUtilizadoPracticas = reactivosUtilizadoPracticas;
    }
   
    public int getIdPractica() {
        return this.idPractica;
    }
    
    public void setIdPractica(int idPractica) {
        this.idPractica = idPractica;
    }
    public UnidadTematica getUnidadTematica() {
        return this.unidadTematica;
    }
    
    public void setUnidadTematica(UnidadTematica unidadTematica) {
        this.unidadTematica = unidadTematica;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Date getCreacion() {
        return this.creacion;
    }
    
    public void setCreacion(Date creacion) {
        this.creacion = creacion;
    }
    public Set getMaterialUtilizados() {
        return this.materialUtilizados;
    }
    
    public void setMaterialUtilizados(Set materialUtilizados) {
        this.materialUtilizados = materialUtilizados;
    }
    public Set getNotificacionesPracticas() {
        return this.notificacionesPracticas;
    }
    
    public void setNotificacionesPracticas(Set notificacionesPracticas) {
        this.notificacionesPracticas = notificacionesPracticas;
    }
    public DatosPractica getDatosPractica() {
        return this.datosPractica;
    }
    
    public void setDatosPractica(DatosPractica datosPractica) {
        this.datosPractica = datosPractica;
    }
    public Set getEquipoUtilizados() {
        return this.equipoUtilizados;
    }
    
    public void setEquipoUtilizados(Set equipoUtilizados) {
        this.equipoUtilizados = equipoUtilizados;
    }
    public Set getReactivosUtilizadoPracticas() {
        return this.reactivosUtilizadoPracticas;
    }
    
    public void setReactivosUtilizadoPracticas(Set reactivosUtilizadoPracticas) {
        this.reactivosUtilizadoPracticas = reactivosUtilizadoPracticas;
    }




}


