package Paquete.Pojos;
// Generated 3/03/2019 08:38:04 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ReporteIncidencia generated by hbm2java
 */
public class ReporteIncidencia  implements java.io.Serializable {


     private int idReporte;
     private SesionDeLaboratorio sesionDeLaboratorio;
     private byte[] nombre;
     private byte[] observaciones;
     private Date fecha;
     private byte[] estado;
     private Date actualizacion;
     private Set historialEmergencias = new HashSet(0);

    public ReporteIncidencia() {
    }

	
    public ReporteIncidencia(int idReporte, SesionDeLaboratorio sesionDeLaboratorio, byte[] nombre, byte[] observaciones, Date fecha, byte[] estado, Date actualizacion) {
        this.idReporte = idReporte;
        this.sesionDeLaboratorio = sesionDeLaboratorio;
        this.nombre = nombre;
        this.observaciones = observaciones;
        this.fecha = fecha;
        this.estado = estado;
        this.actualizacion = actualizacion;
    }
    public ReporteIncidencia(int idReporte, SesionDeLaboratorio sesionDeLaboratorio, byte[] nombre, byte[] observaciones, Date fecha, byte[] estado, Date actualizacion, Set historialEmergencias) {
       this.idReporte = idReporte;
       this.sesionDeLaboratorio = sesionDeLaboratorio;
       this.nombre = nombre;
       this.observaciones = observaciones;
       this.fecha = fecha;
       this.estado = estado;
       this.actualizacion = actualizacion;
       this.historialEmergencias = historialEmergencias;
    }
   
    public int getIdReporte() {
        return this.idReporte;
    }
    
    public void setIdReporte(int idReporte) {
        this.idReporte = idReporte;
    }
    public SesionDeLaboratorio getSesionDeLaboratorio() {
        return this.sesionDeLaboratorio;
    }
    
    public void setSesionDeLaboratorio(SesionDeLaboratorio sesionDeLaboratorio) {
        this.sesionDeLaboratorio = sesionDeLaboratorio;
    }
    public byte[] getNombre() {
        return this.nombre;
    }
    
    public void setNombre(byte[] nombre) {
        this.nombre = nombre;
    }
    public byte[] getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(byte[] observaciones) {
        this.observaciones = observaciones;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public byte[] getEstado() {
        return this.estado;
    }
    
    public void setEstado(byte[] estado) {
        this.estado = estado;
    }
    public Date getActualizacion() {
        return this.actualizacion;
    }
    
    public void setActualizacion(Date actualizacion) {
        this.actualizacion = actualizacion;
    }
    public Set getHistorialEmergencias() {
        return this.historialEmergencias;
    }
    
    public void setHistorialEmergencias(Set historialEmergencias) {
        this.historialEmergencias = historialEmergencias;
    }




}


