package Paquete.Pojos;
// Generated 3/03/2019 08:38:04 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private int idRol;
     private String nombreRol;
     private Set usuarioses = new HashSet(0);
     private Set usuarioses_1 = new HashSet(0);

    public Roles() {
    }

	
    public Roles(int idRol, String nombreRol) {
        this.idRol = idRol;
        this.nombreRol = nombreRol;
    }
    public Roles(int idRol, String nombreRol, Set usuarioses, Set usuarioses_1) {
       this.idRol = idRol;
       this.nombreRol = nombreRol;
       this.usuarioses = usuarioses;
       this.usuarioses_1 = usuarioses_1;
    }
   
    public int getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(int idRol) {
        this.idRol = idRol;
    }
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }
    public Set getUsuarioses_1() {
        return this.usuarioses_1;
    }
    
    public void setUsuarioses_1(Set usuarioses_1) {
        this.usuarioses_1 = usuarioses_1;
    }




}


