package Paquete.Pojos;
// Generated 3/03/2019 08:38:04 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SesionDeLaboratorio generated by hbm2java
 */
public class SesionDeLaboratorio  implements java.io.Serializable {


     private int idSesion;
     private UnidadGrupo unidadGrupo;
     private Date fecha;
     private String docenteAuxiliar;
     private Set historialEquipos = new HashSet(0);
     private Set reactivoUtilizados = new HashSet(0);
     private Set notificacionesSesions = new HashSet(0);
     private Set residuoses = new HashSet(0);
     private Set reporteIncidencias = new HashSet(0);
     private Set vales = new HashSet(0);

    public SesionDeLaboratorio() {
    }

	
    public SesionDeLaboratorio(int idSesion, UnidadGrupo unidadGrupo, Date fecha, String docenteAuxiliar) {
        this.idSesion = idSesion;
        this.unidadGrupo = unidadGrupo;
        this.fecha = fecha;
        this.docenteAuxiliar = docenteAuxiliar;
    }
    public SesionDeLaboratorio(int idSesion, UnidadGrupo unidadGrupo, Date fecha, String docenteAuxiliar, Set historialEquipos, Set reactivoUtilizados, Set notificacionesSesions, Set residuoses, Set reporteIncidencias, Set vales) {
       this.idSesion = idSesion;
       this.unidadGrupo = unidadGrupo;
       this.fecha = fecha;
       this.docenteAuxiliar = docenteAuxiliar;
       this.historialEquipos = historialEquipos;
       this.reactivoUtilizados = reactivoUtilizados;
       this.notificacionesSesions = notificacionesSesions;
       this.residuoses = residuoses;
       this.reporteIncidencias = reporteIncidencias;
       this.vales = vales;
    }
   
    public int getIdSesion() {
        return this.idSesion;
    }
    
    public void setIdSesion(int idSesion) {
        this.idSesion = idSesion;
    }
    public UnidadGrupo getUnidadGrupo() {
        return this.unidadGrupo;
    }
    
    public void setUnidadGrupo(UnidadGrupo unidadGrupo) {
        this.unidadGrupo = unidadGrupo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDocenteAuxiliar() {
        return this.docenteAuxiliar;
    }
    
    public void setDocenteAuxiliar(String docenteAuxiliar) {
        this.docenteAuxiliar = docenteAuxiliar;
    }
    public Set getHistorialEquipos() {
        return this.historialEquipos;
    }
    
    public void setHistorialEquipos(Set historialEquipos) {
        this.historialEquipos = historialEquipos;
    }
    public Set getReactivoUtilizados() {
        return this.reactivoUtilizados;
    }
    
    public void setReactivoUtilizados(Set reactivoUtilizados) {
        this.reactivoUtilizados = reactivoUtilizados;
    }
    public Set getNotificacionesSesions() {
        return this.notificacionesSesions;
    }
    
    public void setNotificacionesSesions(Set notificacionesSesions) {
        this.notificacionesSesions = notificacionesSesions;
    }
    public Set getResiduoses() {
        return this.residuoses;
    }
    
    public void setResiduoses(Set residuoses) {
        this.residuoses = residuoses;
    }
    public Set getReporteIncidencias() {
        return this.reporteIncidencias;
    }
    
    public void setReporteIncidencias(Set reporteIncidencias) {
        this.reporteIncidencias = reporteIncidencias;
    }
    public Set getVales() {
        return this.vales;
    }
    
    public void setVales(Set vales) {
        this.vales = vales;
    }




}


