package Paquete.Pojos;
// Generated 3/03/2019 08:38:04 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vale generated by hbm2java
 */
public class Vale  implements java.io.Serializable {


     private int idVale;
     private Equipo equipo;
     private SesionDeLaboratorio sesionDeLaboratorio;
     private byte[] vale;
     private byte[] status;
     private Set datosVales = new HashSet(0);

    public Vale() {
    }

	
    public Vale(int idVale, Equipo equipo, SesionDeLaboratorio sesionDeLaboratorio, byte[] vale, byte[] status) {
        this.idVale = idVale;
        this.equipo = equipo;
        this.sesionDeLaboratorio = sesionDeLaboratorio;
        this.vale = vale;
        this.status = status;
    }
    public Vale(int idVale, Equipo equipo, SesionDeLaboratorio sesionDeLaboratorio, byte[] vale, byte[] status, Set datosVales) {
       this.idVale = idVale;
       this.equipo = equipo;
       this.sesionDeLaboratorio = sesionDeLaboratorio;
       this.vale = vale;
       this.status = status;
       this.datosVales = datosVales;
    }
   
    public int getIdVale() {
        return this.idVale;
    }
    
    public void setIdVale(int idVale) {
        this.idVale = idVale;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public SesionDeLaboratorio getSesionDeLaboratorio() {
        return this.sesionDeLaboratorio;
    }
    
    public void setSesionDeLaboratorio(SesionDeLaboratorio sesionDeLaboratorio) {
        this.sesionDeLaboratorio = sesionDeLaboratorio;
    }
    public byte[] getVale() {
        return this.vale;
    }
    
    public void setVale(byte[] vale) {
        this.vale = vale;
    }
    public byte[] getStatus() {
        return this.status;
    }
    
    public void setStatus(byte[] status) {
        this.status = status;
    }
    public Set getDatosVales() {
        return this.datosVales;
    }
    
    public void setDatosVales(Set datosVales) {
        this.datosVales = datosVales;
    }




}


